### PR TITLE
Halving benchmarks

### PR DESCRIPTION
**Pull request by amueller**
cc @NicolasHug maybe you can look into this a bit?
I didn't run the SVC gridsearch on MNIST, that would be nice to have as a data point

### CODE REVIEW

**Comment by amueller** [comment]
also the randomized search benchmark requires adjusting the number of iterations of randomized search to take similar time to the successive halving so the numbers are somewhat comparable

**Comment by NicolasHug** [comment]
I'll try to remember to run the benchmark tonight ^^

**Comment by amueller** [comment]
@nicolashug did you?

**Comment by NicolasHug** [comment]
No :/

**Pull request merged**
