### PR TITLE
fix: really long column names mess up plots

### PR DESCRIPTION
**Pull request by kumanday**
Addresses https://github.com/amueller/dabl/issues/148

### CODE REVIEW

**Comment by amueller** [comment]
Thanks! Can you check out the test failure? It seems unrelated but I'm a bit confused.
Also, it looks like now there are two mechanisms for shortening the tick labels. I think it would be nicer if there could be a single mechanisms that's used everywhere, either always trimming after assigning labels or always before.

**Comment by kumanday** [comment]
I'm not sure why the test is failing -- I ran it locally and it passes.
dabl-test-preprocesing

**Comment by kumanday** [comment]
I will try to reproduce the test failure on a Linux system.

Regarding the use of `_short_tick_names`, the function was already there; I simply added some functionality to it.  I agree it would be good to consolidate: I could rename that function and retrofit all previous direct uses of _shortname for shortening tick labels and/or axes labels.

**Comment by amueller** [comment]
Oh you're right, it's my mess not yours ;) So I'm happy to keep it the way it is and leave it for another PR.

**Comment by amueller** [comment]
The test failure is an issue with a change in pandas 1.0. I'm investigating: https://github.com/pandas-dev/pandas/issues/31469

**Comment by amueller** [comment]
can you try merging with master please?

**Comment by kumanday** [comment]
I just reproduced the failed test on a Linux machine and verified that the failure began with this commit: d4cd283fda678adf18070a101473315e562b9e32

**Comment by kumanday** [comment]
Seems to be OK now.

**Comment by kumanday** [comment]
fixes #148 
I realize now "Addresses" is not one of the magic words ;-)

**Comment by kumanday** [comment]
@amueller maybe there's a delay, or maybe you'll have to close the issue manually since I didn't have one of the issue-closing words in a comment _before_ the PR was merged

**Comment by kumanday** [comment]
or.. would you like me to work on the refactoring to standardize the use of a function like `_short_tick_names` before closing the issue?  If so, I'm curious about balancing flexibility with standardization.  Should we allow separate sizing of *x* and *y* labels/ticklabels, or use the same specified length for both dimensions?  The former could get cumbersome with too many arguments.  Perhaps if different x vs. y lengths are ever needed one could just resort to direct calls to _shortname.

**Comment by amueller** [comment]
@encryptedcommerce I'm gonna close it for now. Your work definitely fixed the main issue I had in mind. There is *many* places in dabl that could use a good refactoring. If you want to keep working on making this a bit cleaner, feel free to go ahead, though. And yes, I think using the same length for both is fine.

**Pull request merged**
