### PR TITLE
add legend parameter to mosaic_plot function, default to True

### PR DESCRIPTION
**Pull request by seljukgulcan**
Related discussion #207 

Set True as default value. I'm not sure but it feels like default value should be True as they are util functions.

### CODE REVIEW

**Comment by amueller** [comment]
Thanks! Right now it looks like it adds a legend to each mosaic plot in ``plot``. so the call in ``plot`` probably needs to be adjusted:
https://1096-148831482-gh.circle-artifacts.com/0/doc/auto_examples/plot/plot_splice.html

**Comment by amueller** [comment]
Sorry for the slow reply, I've been traveling.

**Comment by seljukgulcan** [comment]
Thanks for the review.
I want to ask something just to be sure that I understand your comment correctly.

When we plot the data with `plot_classification_categorical` and `kind=count`, only the first plot has a legend. I think we want the same thing with the mosaic plot, right? Only the first plot should have a legend?

**Comment by amueller** [comment]
Yes exactly, I think that's most useful. What do you think?

**Comment by seljukgulcan** [comment]
Done.

**Comment by amueller** [comment]
Sweet, thanks!

**Pull request merged**
