### PR TITLE
Add example for discrete_scatter

### LINKED ISSUE #166: add example for discrete_scatter
Add example for a stand-alone call to discrete_scatter, and maybe add an example to the docstring as well.

### PR DESCRIPTION
**Pull request by SvoONs**
Fix #166 by adding an example file using the `titanic` dataset and also extending the dosctring of `discrete_scatter` with said example.

### CODE REVIEW

**Comment by SvoONs** [comment]
Apparently, I broke the build... I will have a look. Also I noticed the arguments `unique_c` and `clip_outliers` are not documented yet, I will come up with proposals.

**Comment by amueller** [comment]
Thanks, fixing the docs would be very welcome as well!
Hm the same failure is in #180 I must have messed this up myself.

**Comment by amueller** [comment]
Seems like a regression in pandas 1.0 that broke CI: https://github.com/pandas-dev/pandas/issues/31469

**Comment by amueller** [comment]
can you please do another commit to trigger CI again? I just moved the repo to its own org which reset all the CI.

**Comment by amueller** [comment]
hm the failure is related to your change though I'm not entirely sure what's going on. Looks like a bug in the discrete_scatter code maybe?

**Comment by amueller** [comment]
Couldn't reproduce the error locally. Sex might also not be a good example for a scatterplot given that it's categorical. It might work after #175 but right now it'd look pretty boring.

**Comment by SvoONs** [comment]
I can reproduce the error locally using `pandas==1.0.0`. If I downpin pandas tests pass. 
I picked a different dataset for the example, let me know what you think. 
test

**Comment by amueller** [comment]
If you merge master, the error will go away. I pushed a work-around. And yes, that example looks great, thanks!

**Comment by SvoONs** [comment]
I had to create the figure using `plt.figure()` in the docstring example in order to make doctest pass. In my local setup it also works without, a bit weird.

**Comment by amueller** [comment]
That's a bit odd but looks good now! Thanks!

**Pull request merged**
