### PR TITLE
added seaborn jointplot

### PR DESCRIPTION
**Pull request by ADMoreau**
added seaborn jointplot as well as function to remove rows contatining outliers from a two column dataset

### CODE REVIEW

**Comment by amueller** [comment]
Thanks for the PR! Given that this is a very thin wrapper, do you think it would make sense to just provide the clipping function and not wrap the joint plot? That would require two lines to do this instead of one on the side of the user, but also would allow users to use any other plot from seaborn.
The reason why I haven't wrapped this yet is that the way it is implemented, you can't easily create multiple of these within a single figure. I would prefer to have a version of joint_plot that you can apply on a grid.

**Comment by ADMoreau** [comment]
It might make more sense, I think you could add more preprocessing to the
function as well. I thought that was what was wanted from one of the issues
so either way, whichever you think is best for the overall design of the
software is fine with me.

**Comment by amueller** [comment]
Which issue was that? I might need to clarify then.

**Comment by ADMoreau** [comment]
#192

**Comment by amueller** [comment]
Sorry for being unclear. I tried to clarify. I wanted to optionally replace the use of ``discrete_scatter`` with something that can do a density plot. This requires a bit more work than wrapping the jointplot from seaborn as that doesn't allow plotting different classes. Also, use inside ``plot`` requires the ability to pass an axis to plot into, which jointplot can't do. Sorry if I wasted your time by being unclear.

**Comment by ADMoreau** [comment]
Ok, I see what you mean

**Pull request closed without merging**
