### PR TITLE
use safe indexing

### PR DESCRIPTION
**Pull request by amueller**
@NicolasHug I think we need this, but it still doesn't work for pandas dataframe input.

```python
from sklearn.pipeline import make_pipeline
from scipy import stats
from sklearn.model_selection import GridSearchCV
from dabl import EasyPreprocessor
from dabl.preprocessing import clean
from sklearn.tree import DecisionTreeClassifier
import sklearn
sklearn.set_config(print_changed_only=True)

data = pd.read_csv("/home/andy/datasets/adult.csv")
data = pd.read_csv("https://github.com/amueller/ml-workshop-3-of-4/raw/master/notebooks/data/adult.csv")
target = 'income'

param_grid = {'decisiontreeclassifier__max_leaf_nodes': []}
pipe = make_pipeline(EasyPreprocessor(), DecisionTreeClassifier(max_leaf_nodes=100))

from dabl import RandomSuccessiveHalving
param_dist = {'decisiontreeclassifier__max_leaf_nodes': stats.randint(2, 500)}

data = clean(data)
sh.fit(data.drop(target, axis=1), data[target])
```

this gets some duplicate index errors and in the last iteration all scores are nan :-/

### CODE REVIEW

**Comment by NicolasHug** [comment]
It's missing `sh` I can't reproduce ^^
And yes we need `safe_indexing`!

**Comment by amueller** [comment]
Oh sorry sh is just RandomSuccessiveHalving(pipe, param_dist).

**Comment by NicolasHug** [comment]
Ugh, should be `indexes = rng.choice(X.shape[0], r_i, replace=False)`, my bad.

That fixes the duplicate indexes issue but I still NaNs get sometimes.

It comes from this sequence of operations called in `fit()`:

```py
from sklearn.utils import safe_indexing
import numpy as np
from dabl.preprocessing import detect_types

rng = np.random.RandomState(0)

X, y = data.drop(target, axis=1), data[target]
indexes = rng.choice(X.shape[0], 8, replace=False)
X_iter, y_iter = safe_indexing(X, indexes), safe_indexing(y, indexes)

detect_types(X_iter)
```

(Try with a seed of 1 and it will pass)

```pytb
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-195-020bd9b4c78f> in <module>
      9 X_iter, y_iter = safe_indexing(X, indexes), safe_indexing(y, indexes)
     10 
---> 11 detect_types(X_iter)

~/dev/dabl/dabl/preprocessing.py in detect_types(X, type_hints, max_int_cardinality, dirty_float_threshold, near_constant_threshold, verbose)
    173         warn_for = []
    174         for c in suspicious_index.index[suspicious_index]:
--> 175             if X[c][0] == 0:
    176                 if (X[c] == np.arange(X.shape[0])).all():
    177                     # definitely an index

~/.virtualenvs/sklearn/lib/python3.7/site-packages/pandas/core/series.py in __getitem__(self, key)
    866         key = com.apply_if_callable(key, self)
    867         try:
--> 868             result = self.index.get_value(self, key)
    869 
    870             if not is_scalar(result):

~/.virtualenvs/sklearn/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_value(self, series, key)
   4373         try:
   4374             return self._engine.get_value(s, k,
-> 4375                                           tz=getattr(series.dtype, 'tz', None))
   4376         except KeyError as e1:
   4377             if len(self) > 0 and (self.holds_integer() or self.is_boolean()):

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 0
```

I'll take a look at what's going on

**Comment by NicolasHug** [comment]
Right so             `if X[c][0] == 0:` should be `if X[c].iloc[0] == 0:` to avoid the key error, but since `X[c]` is

```
26    19
86    49
2     38
55    43
75    27
93    30
16    25
73    23
Name: age, dtype: int64
```

~~I don't think the check works as expected (Namely, this won't properly be recognized as an index). Not sure what you want to do about it~~ EDIT: Nevermind I think using `iloc` is the right fix. I'll submit a PR

**Comment by amueller** [comment]
oh I fixed that as well at some point.. lol

**Pull request closed without merging**
