### PR TITLE
[MRG] List dependencies in `setup.py` (was: make it launch on mybinder.org)

### PR DESCRIPTION
**Pull request by betatim**
I wanted to play with this and needed to make these tweaks to get it to launch. Installs numpy and scipy and then runs `pip install -e.`

https://mybinder.org/v2/gh/betatim/dabl/betatim-patch-1

### CODE REVIEW

**Comment by amueller** [comment]
Thanks.
It should actually be in the setup.py. I copied stuff from scikit-learn, but we should actually declare dependencies there to be pip installable.

**Comment by amueller** [comment]
also sklearn?

**Comment by NicolasHug** [comment]
I think that's a pretty standard way:

```py
with open(path.join(here, 'requirements.txt'), encoding='utf-8') as f:
    install_requires = f.read().split('\n').strip()

setup(
   # ...
   install_requires=install_requires,
   # ...
)
```

Also pandas, matplotlib, seaborn, ... ?

**Comment by amueller** [comment]
@NicolasHug I think we only need it in the setup.py, I'm opposed to requirements.txt ;)

**Comment by betatim** [comment]
> Also sklearn?

Nods, bumped into that when trying to run the examples.

The reason I added the `requirements.txt` is that the `setup.py` requires that numpy and scipy are already installed when it runs. I didn't investigate if this is actually true or just a left over from using the scikit-learn `setup.py` as a starting point.

If we can organise for all dependencies to be listed in `setup.py` and not need some of them to already be installed we don't need to do anything for it to run on mybinder.org as it will notice the `setup.py` and conclude that what needs doing is `pip install -e.`.

**Comment by amueller** [comment]
thanks! also matplotlib and seaborn probably?

**Comment by amueller** [comment]
but yes, the structure of setup.py was copied from the template project and completely unnecessary

**Comment by betatim** [comment]
Done.

**Comment by amueller** [comment]
Thanks! did you test that it worked? Is there an easy way to test that?

**Comment by betatim** [comment]
Trying it now https://mybinder.org/v2/gh/betatim/dabl/betatim-patch-1

> Is there an easy way to test that?

I have https://addons.mozilla.org/en-US/firefox/addon/open-with-binder/ installed so I tend to head over to the repo (and branch) where the PR comes from and click the extension. Otherwise you'd have to construct the https://mybinder.org/v2/gh/betatim/dabl/betatim-patch-1 link by hand (Not a disaster but lazyness wins).

**Comment by betatim** [comment]
Now that I can fully run the examples: this is a pretty cool library :)

**Comment by amueller** [comment]
Thanks! It has about 5% of the target functionality so far ;)

**Comment by amueller** [comment]
But any feedback and contributions certainly welcome!

**Pull request merged**
