### PR TITLE
Update AnyClassifier Portfolios

### PR DESCRIPTION
**Pull request by hp2500**
I have updated the AnyClassifier portfolios...
- Now the Included portfolios are HGB, SVC, RF, "baseline" and "mixed" (32 classifiers each)
- Submodular optimization was based on rank metric as discussed some time ago
- I have changed the default portfolio to "mixed" and updated the docs

### CODE REVIEW

**Comment by amueller** [comment]
Thanks, that was quick! Does mixed also include RF now?
and the default now doesn't include logistic regression?

Also, I'm not sure how I feel about using black on this. This makes the file huge and hard to read but I don't have a strong opinion. I'm also not sure if we want to list the parameters that are at their default values, as that has led to #238 for example.

**Comment by amueller** [comment]
Oh I see it does include RF, that's awesome! Before making this the new default, maybe we should try some experiments on standard datasets though?

**Comment by hp2500** [comment]
Yes, I haven't run experiments with logistic regression, but RF is fully integrated now.
I can test the portfolio on some standard data sets. I can also include as few parameters as possible. 

What exactly do you mean by "using black"?

**Comment by amueller** [comment]
Awesome!
You used the black code formatter to break all the lines, right? Or how did you get to this formatting?

**Comment by hp2500** [comment]
Aaah ok! I ran it through yapf (https://github.com/google/yapf). Otherwise it takes forever to make everything pep8 compliant.

**Comment by amueller** [comment]
ah, I usually use autopep8. I haven't really seen people use yapf, so I just assumed black ;)

**Comment by hp2500** [comment]
Some notes:
- I have reformatted the portfolio such that it includes no default parameters.
- Newer sklearn versions cap the hgb max_bins parameter at 255, so replaced all 256 with 255 for the sake of compatibility. 
- I have tested the different portfolios on a few classification datasets and performance looks good. However, I think that we should do a more principled assessment. Do you think it would be a good idea to add dabl as an automl framework to the OpenML automlbenchnmark (https://openml.github.io/automlbenchmark/extending.html#adding-an-automl-framework)? That way we would have a fair comparison with other frameworks. I have already forked the repo and will try to implement it.

**Comment by hp2500** [comment]
@amueller quick update: I have started running experiments for LogisticRegression() (i.e., running high performing runs on all benchmark tasks) so that I will be able to select those models into the portfolio.

**Comment by hp2500** [comment]
Notes: 
- Mined top LogisticRegression() runs from openml CC18 tasks and ran each of the setups on all other CC18 tasks.
- Ran additional SVC() runs that were previously missing. This considerably reduced the amount of missing runs.
- Portfolio composition changed a bit. The mixed portfolio contains a LogisticRegression setup. I have also added a LogisticRegression portfolio
-

**Comment by amueller** [comment]
That's awesome!

**Comment by amueller** [comment]
Do you have any plots showing how much this improved the overall portfolio?

**Comment by amueller** [comment]
the file is huge now, do you maybe want to split it into several files? And otherwise is this ready to merge? Have you checked the test failures?

**Comment by hp2500** [comment]
@amueller 
1) I feel like the overall effect on portfolio performance is negligible as LogisticRegression() was rarely among the best setups. The figure also looked pretty much unchanged. I overwrote the old figures, but I am sure I can reproduce them.
2) I have added a package with individual portfolio modules which are imported by pipelines.py 
3) I will check the test failures now

**Comment by hp2500** [comment]
@amueller The remaining Travis error is unrelated to the portfolio classifier, so i think we are ready to merge.

**Comment by amueller** [comment]
awesome, thanks!

**Comment by amueller** [comment]
Hey! do you have the evaluation plots for this? I can't access my Columbia email address any more :(
Also, did you get to run this against the automl benchmark?

**Comment by hp2500** [comment]
Hi, here are the latest evaluation plots.

By mean AUC:
image

By mean inverted rank index: 
image

I tried to run the automl benchmark a few weeks ago after I saw that you fixed the original issue, but I ran into different problems. I'll try again this week!

**Pull request merged**
